BUILD_FILE_CONTENT = """# This file was automatically generated by rules_conda
package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")

py_runtime_pair(
    name = "runtimes",
    py2_runtime = {py2_runtime},
    py3_runtime = {py3_runtime}
)

toolchain(
    name = "{toolchain_name}",
    toolchain = ":runtimes",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
"""

def _toolchain_impl(repository_ctx):
    py2_runtime=repository_ctx.attr.py2_runtime
    py3_runtime=repository_ctx.attr.py3_runtime

    # python2_runtime can be None, in this case insert string None
    py2_runtime_value = "\"{}\"".format(py2_runtime) if py2_runtime else "None"
    py3_runtime_value = "\"{}\"".format(py3_runtime)

    # create BUILD file with toolchain definition
    repository_ctx.file(
        "BUILD",
        content = BUILD_FILE_CONTENT.format(py2_runtime=py2_runtime_value, 
                                            py3_runtime=py3_runtime_value,
                                            toolchain_name=repository_ctx.attr.toolchain_name)
    )

toolchain_rule = repository_rule(
    _toolchain_impl,
    attrs = {
        "py2_runtime": attr.label(mandatory=False),
        "py3_runtime": attr.label(mandatory=True),
        "toolchain_name": attr.string(mandatory=True)
    }
)