load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
)

local_repository(
    name = "rules_conda",
    path = "../../../",
)

load("@rules_conda//:defs.bzl", "conda_create", "load_conda", "register_toolchain")

load_conda(
    install_mamba = True,
    quiet = False,
)

conda_create(
    name = "test_env",
    timeout = 600,
    clean = False,
    environment = "@//:environment.yml",
    quiet = False,
    use_mamba = True,
)

register_toolchain(env = "test_env")
