BUILD_FILE_CONTENT = """# This file was automatically generated by rules_conda
package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")

py_runtime_pair(
    name = "runtimes",
    py3_runtime = "{runtime}"
)

toolchain(
    name = "{toolchain_name}",
    toolchain = ":runtimes",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
"""

def _toolchain_impl(rctx):
    runtime = rctx.attr.runtime

    # create BUILD file with toolchain definition
    rctx.file(
        "BUILD",
        content = BUILD_FILE_CONTENT.format(
            runtime = runtime,
            toolchain_name = rctx.attr.toolchain_name,
        ),
    )

toolchain_rule = repository_rule(
    _toolchain_impl,
    attrs = {
        "runtime": attr.label(mandatory = True),
        "toolchain_name": attr.string(mandatory = True),
    },
)
