name: Running tests

on:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"

# env for all jobs
env:
  BAZELISK_CACHE_DIR: ~/.cache/bazelisk
  BAZEL_CACHE_DIR: ~/.cache/bazel
  # increase this value to manually reset cache
  CACHE_NUMBER: 0

jobs:
  test:
    name: Run tests
    strategy:
      # don't stop all tests if one fails
      fail-fast: false
      matrix:
        # better to use pinned versions here
        config:
          - { os: ubuntu-latest, shell: bash -l, script: ./scripts/tests.sh }
          - { os: macos-latest, shell: bash -l, script: ./scripts/tests.sh }
          - { os: windows-latest, shell: cmd /C CALL, script: .\scripts\tests }
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }} {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache bazelisk
        uses: actions/cache@v2
        with:
          path: ${{ env.BAZELISK_CACHE_DIR }}
          key: ${{ runner.os }}-bazelisk-${{ env.CACHE_NUMBER }}
      - name: Cache bazel
        uses: actions/cache@v2
        with:
          path: ${{ env.BAZEL_CACHE_DIR }}
          key: ${{ runner.os }}-bazel-${{ env.CACHE_NUMBER }}
      - name: Run tests
        run: ${{ matrix.config.script }}
